name: final_project
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  flutter_local_notifications: ^18.0.1
  timezone: ^0.10.0
  flutter_timezone: ^3.0.1
  awesome_notifications: ^0.10.0
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  http: ^1.2.2
  intl: ^0.19.0
  path_provider: ^2.1.5
  flutter_secure_storage: ^9.2.2
  dotted_border: ^2.0.0+3
  flutter_application_1: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.3.3
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  #assets:
   # 
